name: Continuous Integration

on: [push, pull_request]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # - name: Setup Miniconda
      #   uses: conda-incubator/setup-miniconda@v2
      #   with:
      #     auto-update-conda: true
      #     python-version: '3.8'
      #     environment-file: environment.yml
      #     activate-environment: $(PROJECT_NAME)

      # - name: Lint with flake8
      #   run: |
      #     # Activates the Conda environment and then lints the project.
      #     echo "Activating Conda environment."
      #     source activate $(PROJECT_NAME)
      #     echo "Linting with flake8."
      #     flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
      #     flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Test with pytest
        run: |
          # Assumes tests are setup to run with pytest
          pip install pytest
          echo "Testing with pytest."
          pytest

      - name: Trigger Jenkins Job for Further Actions
        if: success()
        uses: appleboy/jenkins-action@master
        with:
          jenkins_url: ${{ secrets.JENKINS_URL }}
          jenkins_user: ${{ secrets.JENKINS_USER }}
          jenkins_token: ${{ secrets.JENKINS_TOKEN }}
          job_name: "usl_for_embedding_gpu-intensive_tasks"
          parameters: COMMIT_SHA=${{ github.sha }}
        env:
          JENKINS_URL: ${{ secrets.JENKINS_URL }}
          JENKINS_USER: ${{ secrets.JENKINS_USER }}
          JENKINS_TOKEN: ${{ secrets.JENKINS_TOKEN }}
